const actions = {
   STORE_CURRENT_USER: "STORE_CURRENT_USER",
   STORE_QUEUED_CARDS: "STORE_QUEUED_CARDS",
   UPDATE_INDEX_OF_CURRENT_CARD: " UPDATE_INDEX_OF_CURRENT_CARD",
   RESET_QUEUE: "RESET_QUEUE",
};

export default actions;
